# Generated by Django 5.2.2 on 2025-06-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('practitioner_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'doctors',
                'indexes': [models.Index(fields=['city'], name='doctors_city_32a444_idx'), models.Index(fields=['state'], name='doctors_state_e56250_idx'), models.Index(fields=['zip_code'], name='doctors_zip_cod_c80a05_idx')],
            },
        ),
    ]
