# Generated by Django 5.2.2 on 2025-06-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhirapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='verified',
        ),
    ]
