# Generated by Django 5.2.2 on 2025-06-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirapi', '0002_remove_doctor_verified'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialization'], name='doctors_special_6661e0_idx'),
        ),
    ]
