# Generated by Django 5.2.2 on 2025-06-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirapi', '0005_alter_appointment_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
